<?php
// src/AppBundle/Controller/KnowledgeController.php
namespace AppBundle\Controller;

use AppBundle\Entity\Action;
use AppBundle\Entity\Knowledge;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class KnowledgeController extends BaseAdminController
{
    protected function listAction()
    {
        /** @var User $user */
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $userCompany = $user->getCompany();

        $this->entity['list']['dql_filter'] = $user->hasRole("ROLE_SUPER_ADMIN")
            ? $this->entity['list']['dql_filter']
            : "entity.company = " . $userCompany->getId();

        return parent::listAction(); // TODO: Change the autogenerated stub
    }

    protected function searchAction()
    {
        /** @var User $user */
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $userCompany = $user->getCompany();

        $this->entity['search']['dql_filter'] = $user->hasRole("ROLE_SUPER_ADMIN")
            ? $this->entity['list']['dql_filter']
            : "entity.company = " . $userCompany->getId();

        return parent::searchAction(); // TODO: Change the autogenerated stub
    }

    protected function showAction()
    {
        $id = $this->request->query->get('id');

        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $currentUserCompany = $currentUser->getCompany();

        /** @var Knowledge $requestedKnowledge */
        $requestedKnowledge = $this->em->getRepository("AppBundle:Knowledge")->find($id);
        $requestedKnowledgeCompany = $requestedKnowledge->getCompany();

        if (
            !$currentUser->hasRole("ROLE_SUPER_ADMIN") &&
            $currentUserCompany->getId() != $requestedKnowledgeCompany->getId()
        ) {
            throw new AccessDeniedException('You cant be here');
        }

        return parent::showAction(); // TODO: Change the autogenerated stub
    }

    protected function editAction()
    {
        $id = $this->request->query->get('id');

        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $currentUserCompany = $currentUser->getCompany();

        /** @var Knowledge $requestedKnowledge */
        $requestedKnowledge = $this->em->getRepository("AppBundle:Knowledge")->find($id);
        $requestedKnowledgeCompany = $requestedKnowledge->getCompany();

        if (
            !$currentUser->hasRole("ROLE_SUPER_ADMIN") &&
            $currentUserCompany->getId() != $requestedKnowledgeCompany->getId()
        ) {
            throw new AccessDeniedException('You cant be here');
        }

        return parent::editAction(); // TODO: Change the autogenerated stub
    }

    protected function deleteAction()
    {
        $id = $this->request->query->get('id');

        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $currentUserCompany = $currentUser->getCompany();

        /** @var Knowledge $requestedKnowledge */
        $requestedKnowledge = $this->em->getRepository("AppBundle:Knowledge")->find($id);
        $requestedKnowledgeCompany = $requestedKnowledge->getCompany();

        if (
            !$currentUser->hasRole("ROLE_SUPER_ADMIN") &&
            $currentUserCompany->getId() != $requestedKnowledgeCompany->getId()
        ) {
            throw new AccessDeniedException('You cant be here');
        }

        return parent::deleteAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Knowledge $entity
     * @param array $entityProperties
     * @return \Symfony\Component\Form\Form
     */
    protected function createEditForm($entity, array $entityProperties)
    {
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $form = parent::createEditForm($entity, $entityProperties);

        if (!$currentUser->hasRole("ROLE_SUPER_ADMIN")) {
            $form->remove("company");
            $this->setActionsFormInput($form, $currentUser->getCompany()->getId());
        } else {
            $this->setActionsFormInput($form, $entity->getCompany()->getId());
        }

        return $form;
    }

    protected function createNewForm($entity, array $entityProperties)
    {
        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $form = parent::createNewForm($entity, $entityProperties);

        if (!$currentUser->hasRole("ROLE_SUPER_ADMIN")) {
            $form->remove("company");
            $this->setActionsFormInput($form, $currentUser->getCompany()->getId());
        }

        return $form;
    }

    /**
     * @param Knowledge $entity
     */
    protected function prePersistEntity($entity)
    {
        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        if (!$currentUser->hasRole("ROLE_SUPER_ADMIN")) {
            $entity->setCompany($currentUser->getCompany());
        }

        parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

    protected function setActionsFormInput ($form, $companyId = 0)
    {
        $form->add('actions', EntityType::class, array(
            'class' => 'AppBundle:Action',
            'required' => false,
            'multiple' => true,
            'query_builder' => function (EntityRepository $repository) use ($companyId) {
                $qb = $repository->createQueryBuilder('a');
                return $qb
                    ->where("a.company = :companyId")
                    ->setParameter("companyId", $companyId);
            }
        ));
    }


    /**
     * Returns a JSON string with the $actions of the Company with the providen id.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function listActionsOfCompanyAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $actionsRepo = $em->getRepository("AppBundle:Action");

        $actions = $actionsRepo->createQueryBuilder("a")
            ->where("a.company = :companyId")
            ->setParameter("companyId", $request->query->get("company_id"))
            ->getQuery()
            ->getResult();

        $responseArray = array();
        /** @var Action $action */
        foreach($actions as $action){
            $responseArray[] = array(
                "id" => $action->getId(),
                "name" => $action->getName()
            );
        }

        return new JsonResponse($responseArray);
    }
}