<?php
// src/AppBundle/Controller/ProductController.php
namespace AppBundle\Controller;

use AppBundle\Entity\Knowledge;
use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class ProductController extends BaseAdminController
{

    protected function listAction()
    {
        /** @var User $user */
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $userCompany = $user->getCompany();

        $this->entity['list']['dql_filter'] = $user->hasRole("ROLE_SUPER_ADMIN")
            ? $this->entity['list']['dql_filter']
            : "entity.company = " . $userCompany->getId();

        return parent::listAction(); // TODO: Change the autogenerated stub
    }

    protected function searchAction()
    {
        /** @var User $user */
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $userCompany = $user->getCompany();

        $this->entity['search']['dql_filter'] = $user->hasRole("ROLE_SUPER_ADMIN")
            ? $this->entity['list']['dql_filter']
            : "entity.company = " . $userCompany->getId();

        return parent::searchAction(); // TODO: Change the autogenerated stub
    }

    protected function showAction()
    {
        $id = $this->request->query->get('id');

        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $currentUserCompany = $currentUser->getCompany();

        /** @var Product $requestedProduct */
        $requestedProduct = $this->em->getRepository("AppBundle:Product")->find($id);
        $requestedProductCompany = $requestedProduct->getCompany();

        if (
            !$currentUser->hasRole("ROLE_SUPER_ADMIN") &&
            $currentUserCompany->getId() != $requestedProductCompany->getId()
        ) {
            throw new AccessDeniedException('You cant be here');
        }

        return parent::showAction(); // TODO: Change the autogenerated stub
    }

    protected function editAction()
    {
        $id = $this->request->query->get('id');

        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $currentUserCompany = $currentUser->getCompany();

        /** @var Product $requestedProduct */
        $requestedProduct = $this->em->getRepository("AppBundle:Product")->find($id);
        $requestedProductCompany = $requestedProduct->getCompany();

        if (
            !$currentUser->hasRole("ROLE_SUPER_ADMIN") &&
            $currentUserCompany->getId() != $requestedProductCompany->getId()
        ) {
            throw new AccessDeniedException('You cant be here');
        }

        return parent::editAction(); // TODO: Change the autogenerated stub
    }

    protected function deleteAction()
    {
        $id = $this->request->query->get('id');

        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $currentUserCompany = $currentUser->getCompany();

        /** @var Product $requestedProduct */
        $requestedProduct = $this->em->getRepository("AppBundle:Product")->find($id);
        $requestedProductCompany = $requestedProduct->getCompany();

        if (
            !$currentUser->hasRole("ROLE_SUPER_ADMIN") &&
            $currentUserCompany->getId() != $requestedProductCompany->getId()
        ) {
            throw new AccessDeniedException('You cant be here');
        }

        return parent::deleteAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Product $entity
     * @param array $entityProperties
     * @return \Symfony\Component\Form\Form
     */
    protected function createEditForm($entity, array $entityProperties)
    {
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $form = parent::createEditForm($entity, $entityProperties);

        if (!$currentUser->hasRole("ROLE_SUPER_ADMIN")) {
            $form->remove("company");
            $this->setKnowledgesFormInput($form, $currentUser->getCompany()->getId());
        } else {
            $this->setKnowledgesFormInput($form, $entity->getCompany()->getId());
        }

        return $form;
    }

    protected function createNewForm($entity, array $entityProperties)
    {
        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $form = parent::createNewForm($entity, $entityProperties);

        if (!$currentUser->hasRole("ROLE_SUPER_ADMIN")) {
            $form->remove("company");
            $this->setKnowledgesFormInput($form, $currentUser->getCompany()->getId());
        }

        return $form;
    }

    /**
     * @param Knowledge $entity
     */
    protected function prePersistEntity($entity)
    {
        /** @var User $currentUser */
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        if (!$currentUser->hasRole("ROLE_SUPER_ADMIN")) {
            $entity->setCompany($currentUser->getCompany());
        }

        parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

    protected function setKnowledgesFormInput ($form, $companyId = 0)
    {
        $form->add('knowledges', EntityType::class, array(
            'class' => 'AppBundle:Knowledge',
            'required' => false,
            'multiple' => true,
            'query_builder' => function (EntityRepository $repository) use ($companyId) {
                $qb = $repository->createQueryBuilder('k');
                return $qb
                    ->where("k.company = :companyId")
                    ->setParameter("companyId", $companyId);
            }
        ));
    }


    /**
     * Returns a JSON string with the $knowledges of the Company with the provided id.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function listKnowledgesOfCompanyAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $knowledgesRepo = $em->getRepository("AppBundle:Knowledge");

        $knowledges = $knowledgesRepo->createQueryBuilder("k")
            ->where("k.company = :companyId")
            ->setParameter("companyId", $request->query->get("company_id"))
            ->getQuery()
            ->getResult();

        $responseArray = array();
        /** @var Knowledge $knowledge */
        foreach($knowledges as $knowledge){
            $responseArray[] = array(
                "id" => $knowledge->getId(),
                "name" => $knowledge->getName()
            );
        }

        return new JsonResponse($responseArray);
    }

    /**
     * Returns a JSON string with the products of the Company with the providen id.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function listProductsOfCompanyAction(Request $request)
    {
        // Get Entity manager and repository
        $em = $this->getDoctrine()->getManager();
        $productsRepo = $em->getRepository("AppBundle:Product");

        // Search the products that belongs to the company with the given id as GET parameter "company_id"
        $products = $productsRepo->createQueryBuilder("p")
            ->where("p.company = :companyId")
            ->setParameter("companyId", $request->query->get("company_id"))
            ->getQuery()
            ->getResult();

        // Serialize into an array the data that we need, in this case only name and id
        // Note: you can use a serializer as well, for explanation purposes, we'll do it manually
        $responseArray = array();
        /** @var Product $product */
        foreach($products as $product){
            $responseArray[] = array(
                "id" => $product->getId(),
                "name" => $product->getName()
            );
        }

        // Return array with structure of the products of the providen company id
        return new JsonResponse($responseArray);
    }
}