<?php

namespace AppBundle\Repository;

/**
 * CnaeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CnaeRepository extends \Doctrine\ORM\EntityRepository
{
}
