<?php

namespace AppBundle\Repository;

/**
 * KnowledgeGeneralLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KnowledgeGeneralLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
