<?php

namespace AppBundle\Repository;

/**
 * KnowledgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KnowledgeRepository extends \Doctrine\ORM\EntityRepository
{
}
