<?php

namespace AppBundle\Repository;

/**
 * PollUserAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollUserAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
