<?php

namespace AppBundle\Repository;

/**
 * PollRegistryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRegistryRepository extends \Doctrine\ORM\EntityRepository
{
}
