<?php

namespace AppBundle\Repository;

/**
 * PollQuestionResponseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionResponseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
