<?php

namespace AppBundle\Repository;

/**
 * PollQuestionAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
