<?php

namespace AppBundle\Repository;

/**
 * PollQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
