<?php

namespace AppBundle\Repository;

/**
 * PollQuestionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollQuestionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
