# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.easyadmin.security:
        class: AppBundle\Security\EasyAdminSecurityEventSubscriber
        arguments: ['@security.access.decision_manager', '@security.token_storage']
        tags:
        - { name: kernel.event_subscriber }

    event.jwt_created_listener:
        class: AppBundle\Event\Listener\JWTCreatedListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    user.mailer.rest:
        class: AppBundle\Mailer\RestMailer
        public: false
        parent: fos_user.mailer.twig_swift